/**
 * Действия, попадающие в журнал. Именованные константы, а не строки по месту
 * вызова: опечатка в строке молча создаст новый вид действия, и фильтр по журналу
 * его не найдёт.
 *
 * Набор дополняется по мере появления разделов.
 */
export const AUDIT_ACTIONS = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_CREATED: 'USER_CREATED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  KASPI_CATALOG_PREVIEW: 'KASPI_CATALOG_PREVIEW',
  KASPI_WAREHOUSES_SAVED: 'KASPI_WAREHOUSES_SAVED',
  KASPI_CABINET_FETCH: 'KASPI_CABINET_FETCH',
  KASPI_PRODUCTS_IMPORTED: 'KASPI_PRODUCTS_IMPORTED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_RENAMED: 'CATEGORY_RENAMED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',
  CATEGORIES_REORDERED: 'CATEGORIES_REORDERED',
  PRODUCTS_CATEGORY_CHANGED: 'PRODUCTS_CATEGORY_CHANGED',
  KASPI_ORDERS_SYNCED: 'KASPI_ORDERS_SYNCED',
  PRODUCTS_RENAMED: 'PRODUCTS_RENAMED',
  SALES_POINT_CREATED: 'SALES_POINT_CREATED',
  SALES_POINT_RENAMED: 'SALES_POINT_RENAMED',
  SALES_POINT_CLOSED: 'SALES_POINT_CLOSED',
  SALES_POINT_REOPENED: 'SALES_POINT_REOPENED',
  DICTIONARY_ITEM_CREATED: 'DICTIONARY_ITEM_CREATED',
  DICTIONARY_ITEM_RENAMED: 'DICTIONARY_ITEM_RENAMED',
  DICTIONARY_ITEM_CLOSED: 'DICTIONARY_ITEM_CLOSED',
  DICTIONARY_ITEM_REOPENED: 'DICTIONARY_ITEM_REOPENED',
  OFFLINE_ORDERS_IMPORTED: 'OFFLINE_ORDERS_IMPORTED',
  SUPPLIERS_IMPORTED: 'SUPPLIERS_IMPORTED',
  SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
  MOYSKLAD_PRODUCTS_IMPORTED: 'MOYSKLAD_PRODUCTS_IMPORTED',
  MOYSKLAD_STOCK_IMPORTED: 'MOYSKLAD_STOCK_IMPORTED',
  KASPI_CABINET_ACCOUNT_SAVED: 'KASPI_CABINET_ACCOUNT_SAVED',
  KASPI_CABINET_CHECKED: 'KASPI_CABINET_CHECKED',
  WORKER_SETTINGS_UPDATED: 'WORKER_SETTINGS_UPDATED',
  WAREHOUSE_UPDATED: 'WAREHOUSE_UPDATED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

/** Подписи действий для журнала в интерфейсе. */
export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  USER_LOGIN: 'Вход в систему',
  USER_LOGIN_FAILED: 'Неудачная попытка входа',
  USER_LOGOUT: 'Выход из системы',
  USER_CREATED: 'Создан сотрудник',
  USER_ROLE_CHANGED: 'Изменена роль',
  USER_DEACTIVATED: 'Сотрудник отключён',
  KASPI_CATALOG_PREVIEW: 'Синхронизация с Kaspi (предпросмотр)',
  KASPI_WAREHOUSES_SAVED: 'Сохранены склады из выгрузки Kaspi',
  KASPI_CABINET_FETCH: 'Загрузка каталога из кабинета Kaspi',
  KASPI_PRODUCTS_IMPORTED: 'Сохранены товары из кабинета Kaspi',
  CATEGORY_CREATED: 'Создана категория товаров',
  CATEGORY_RENAMED: 'Категория переименована',
  CATEGORY_DELETED: 'Категория удалена',
  CATEGORIES_REORDERED: 'Изменён порядок категорий',
  PRODUCTS_CATEGORY_CHANGED: 'Товары перемещены в категорию',
  KASPI_ORDERS_SYNCED: 'Синхронизация заказов Kaspi',
  PRODUCTS_RENAMED: 'Товары переименованы пачкой',
  SALES_POINT_CREATED: 'Создана точка продаж',
  SALES_POINT_RENAMED: 'Точка продаж переименована',
  SALES_POINT_CLOSED: 'Точка продаж закрыта',
  SALES_POINT_REOPENED: 'Точка продаж открыта заново',
  DICTIONARY_ITEM_CREATED: 'Добавлено значение в справочник',
  DICTIONARY_ITEM_RENAMED: 'Значение справочника переименовано',
  DICTIONARY_ITEM_CLOSED: 'Значение справочника закрыто',
  DICTIONARY_ITEM_REOPENED: 'Значение справочника открыто заново',
  OFFLINE_ORDERS_IMPORTED: 'Импорт продаж офлайн-точки',
  SUPPLIERS_IMPORTED: 'Импорт поставщиков из МойСклада',
  SUPPLIER_UPDATED: 'Карточка поставщика изменена',
  MOYSKLAD_PRODUCTS_IMPORTED: 'Импорт закупки и складов из МойСклада',
  MOYSKLAD_STOCK_IMPORTED: 'Импорт остатков из МойСклада',
  KASPI_CABINET_ACCOUNT_SAVED: 'Изменены данные входа в кабинет Kaspi',
  KASPI_CABINET_CHECKED: 'Проверка подключения к кабинету Kaspi',
  WORKER_SETTINGS_UPDATED: 'Изменены настройки воркера',
  WAREHOUSE_UPDATED: 'Изменён склад',
};
